version: '3'
services:
  master:
    build: ./
    image: station
    command: '--version'
  junctiona:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctiona busportf busportj stationk busportn stationo
    ports:
      - '4001:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  busportb:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportb stationc terminalh junctionm stationo junctionq busportr
    ports:
      - '4002:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  stationc:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationc busportb terminald busportj terminalp
    ports:
      - '4003:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  terminald:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminald stationc busportj junctionm
    ports:
      - '4004:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  junctione:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctione terminalh
    ports:
      - '4005:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  busportf:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportf junctiona junctioni terminall
    ports:
      - '4006:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  stationg:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationg junctioni busportn stationo
    ports:
      - '4007:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  terminalh:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalh busportb junctione junctionq
    ports:
      - '4008:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  junctioni:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctioni busportf stationg busportn terminalp
    ports:
      - '4009:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  busportj:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportj junctiona stationc terminald busportn
    ports:
      - '4010:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  stationk:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationk junctiona
    ports:
      - '4011:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  terminall:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminall busportf busportr
    ports:
      - '4012:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  junctionm:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionm busportb terminald stationo terminalp
    ports:
      - '4013:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  busportn:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportn junctiona stationg junctioni busportj
    ports:
      - '4014:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  stationo:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationo junctiona busportb stationg junctionm
    ports:
      - '4015:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  terminalp:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalp stationc junctioni junctionm
    ports:
      - '4016:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  junctionq:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionq busportb terminalh
    ports:
      - '4017:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
  busportr:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportr busportb terminall
    ports:
      - '4018:3000'
    volumes:
      - './src:/app/src'
      - './timetables/18:/app/timetables'
