version: '3'
services:
  master:
    build: ./
    image: station
    command: '--version'
  junctiona:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctiona busportj busportr
    ports:
      - '4001:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportb:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportb busportf terminalp terminalt
    ports:
      - '4002:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationc:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationc terminald busportf stationg terminalh busportn terminalp terminalt
    ports:
      - '4003:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminald:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminald stationc junctione stationg junctionm junctionq
    ports:
      - '4004:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctione:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctione terminald
    ports:
      - '4005:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportf:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportf busportb stationc busportn junctionq busportr
    ports:
      - '4006:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationg:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationg stationc terminald busportj stationk terminalp busportr terminalt
    ports:
      - '4007:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminalh:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalh stationc
    ports:
      - '4008:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctioni:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctioni busportj stationk terminall busportn stationo terminalt
    ports:
      - '4009:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportj:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportj junctiona stationg junctioni junctionm stationo junctionq stations terminalt
    ports:
      - '4010:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationk:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationk stationg junctioni busportr
    ports:
      - '4011:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminall:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminall junctioni junctionm busportn stationo junctionq busportr
    ports:
      - '4012:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionm:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionm terminald busportj terminall stations terminalt
    ports:
      - '4013:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportn:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportn stationc busportf junctioni terminall
    ports:
      - '4014:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationo:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationo junctioni busportj terminall
    ports:
      - '4015:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminalp:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalp busportb stationc stationg stations
    ports:
      - '4016:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionq:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionq terminald busportf busportj terminall terminalt
    ports:
      - '4017:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportr:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportr junctiona busportf stationg stationk terminall stations
    ports:
      - '4018:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stations:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stations busportj junctionm terminalp busportr terminalt
    ports:
      - '4019:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminalt:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalt busportb stationc stationg junctioni busportj junctionm junctionq stations
    ports:
      - '4020:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
