version: '3'
services:
  master:
    build: ./
    image: station
    command: '--version'
  terminala:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminala busporto terminalq busports
    ports:
      - '4001:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionb:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionb junctionf stationl busporto
    ports:
      - '4002:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportc:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportc junctionf terminalm busporto
    ports:
      - '4003:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationd:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationd busportg stationh junctionj terminalq stationt
    ports:
      - '4004:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminale:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminale stationt
    ports:
      - '4005:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionf:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionf junctionb busportc busportk
    ports:
      - '4006:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportg:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportg stationd stationh terminali stationl terminalm stationp
    ports:
      - '4007:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationh:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationh stationd busportg busporto terminalq junctionr
    ports:
      - '4008:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminali:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminali busportg busportk terminalm
    ports:
      - '4009:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionj:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionj stationd stationt
    ports:
      - '4010:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busportk:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busportk junctionf terminali stationl junctionr
    ports:
      - '4011:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationl:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationl junctionb busportg busportk stationp terminalq stationt
    ports:
      - '4012:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminalm:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalm busportc busportg terminali junctionr
    ports:
      - '4013:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionn:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionn junctionr
    ports:
      - '4014:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busporto:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busporto terminala junctionb busportc stationh busports
    ports:
      - '4015:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationp:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationp busportg stationl stationt
    ports:
      - '4016:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  terminalq:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts terminalq terminala stationd stationh stationl busports
    ports:
      - '4017:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  junctionr:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts junctionr stationh busportk terminalm junctionn
    ports:
      - '4018:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  busports:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts busports terminala busporto terminalq
    ports:
      - '4019:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
  stationt:
    image: station
    command: run --unstable --allow-read --allow-net /app/src/main.ts stationt stationd terminale junctionj stationl stationp
    ports:
      - '4020:3000'
    volumes:
      - './src:/app/src'
      - './timetables/20:/app/timetables'
